### ISSUE TITLE
No license for repo

### ISSUE THREAD

**Issue by NatTuck** [jojojames/PhxSocketCPP#2]
This code doesn't have a license statement. The default is copyright ("all rights reserved, no license to use"). I'd like to consider this code for a program I'm working on, but it's currently illegal.

If that wasn't your intent, adding an explicit license statement would be great: https://choosealicense.com/

Thanks!

**Comment by jojojames** [comment]
I'll add a GPL3 license when I get a chance or take a PR for it.

Thanks for the reminder.
